spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    platform: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
  database:
    driverClassName: org.postgresql.Driver
